### ISSUE TITLE
TypeError when using gql.auto with future annotations

### ISSUE THREAD

**Issue by gary-arcana** [blb-ventures/strawberry-django-plus#81]
TypeError: SectorType fields cannot be resolved. Unexpected type 'typing_extensions.Annotated[typing.Any, <auto>]'

```
from __future__ import annotations
from strawberry_django_plus import gql

@gql.django.type(Sector)
class SectorType:
    name: auto
```

**Comment by bellini666** [comment]
I saw that there was a fix today in `strawberry` that might have fixed this issue. Maybe you will have to import `auto` from `strawberry` instead of using `gql.auto`

Can you confirm that it fixed the issue? Also, can you confirm if it works with `gql.auto` or only `strawwberry.auto`?

**Comment by bellini666** [comment]
I also released a fix in this lib that should solve your issues. Please tell me if not so that I can reopen this issue.

**Comment by gary-arcana** [comment]
Hi @bellini666 , I am still having the problem with gql.auto. 

Strawberry.auto works fine.

Here is some more information:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/graphql/type/definition.py", line 800, in fields
    fields = resolve_thunk(self._fields)
  File "/usr/local/lib/python3.8/site-packages/graphql/type/definition.py", line 300, in resolve_thunk
    return thunk() if callable(thunk) else thunk
  File "/usr/local/lib/python3.8/site-packages/strawberry/schema/schema_converter.py", line 396, in <lambda>
    fields=lambda: self.get_graphql_fields(object_type),
  File "/usr/local/lib/python3.8/site-packages/strawberry/schema/schema_converter.py", line 293, in get_graphql_fields
    return self._get_thunk_mapping(
  File "/usr/local/lib/python3.8/site-packages/strawberry/schema/schema_converter.py", line 287, in _get_thunk_mapping
    thunk_mapping[name_converter(f)] = field_converter(f)
  File "/usr/local/lib/python3.8/site-packages/strawberry/schema/schema_converter.py", line 216, in from_field
    field_type = cast(GraphQLOutputType, self.from_maybe_optional(field.type))
  File "/usr/local/lib/python3.8/site-packages/strawberry/schema/schema_converter.py", line 552, in from_maybe_optional
    return GraphQLNonNull(self.from_type(type_))
  File "/usr/local/lib/python3.8/site-packages/strawberry/schema/schema_converter.py", line 584, in from_type
    raise TypeError(f"Unexpected type '{type_}'")
TypeError: Unexpected type 'typing_extensions.Annotated[typing.Any, <auto>]'
```

```
graphql-core==3.2.1
strawberry-django-plus==1.20.0
strawberry-graphql==0.119.1
strawberry-graphql-django==0.4.0
```

**Comment by bellini666** [comment]
Hey @gary-arcana ,

Yeah, unfortunately `gql.auto` will not work with `__future__` annotations  due to how `strawberry` checks for it.

But at runtime `gql.auto` is literally the same as `strawberry.auto`, so you can use it instead.
